version: "3.8"

services:
  timesheetsystem:
    build:
      context: .
      dockerfile: TimesheetSystem/Dockerfile # Adjust if your Dockerfile is elsewhere
      args:
        BUILD_CONFIGURATION: Release
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development